### PR TITLE
bump discourse to v2.4.2

### PR DESCRIPTION
**Pull request by francisco-core**

### CODE REVIEW

**Comment by francisco-core** [comment]
It seems like the build for this failed. I think we need to deploy this manually to see the error it gives

**Comment by anadahz** [comment]
> It seems like the build for this failed. I think we need to deploy this manually to see the error it gives

This is the error from Travis build:
`The job exceeded the maximum log length, and has been terminated.`

The build has failed because Discourse is very verbose and creates a hug
e log and Travis has [a log limit of 4M](https://github.com/travis-ci/travis-ci/issues/1382).
However if we don't make Discourse verbose the build will due to inactivity as Discourse needs more than 10 minutes to build.

Any suggestions?

**Comment by francisco-core** [comment]
What about:

```yaml
- name: some task
  cmd: "./launcher rebuild app"
  no_log: True
```

**Comment by anadahz** [comment]
Thx @francisco-core it looks good to me.
LGTM.

**Comment by francisco-core** [comment]
Cool @anadahz I've now successfully deployed this branch on the prod server.
Merging

**Pull request merged**
