### PR TITLE
bump discourse to v2.7.0

### PR DESCRIPTION
**Pull request by francisco-core**

### CODE REVIEW

**Comment by francisco-core** [comment]
I'm having issues with the deployment @anadahz. I believe it has to do with MAXMIND DB yet again...

```
I, [2021-05-22T11:27:42.338558 #823]  INFO -- : Writing /var/www/discourse/public/assets/discourse-widget-hbs/package-bb2aba620aebf0e76c5c820ef1b5c45b36408d699bfed67278a1011137b28912.json
I, [2021-05-22T11:27:42.359652 #823]  INFO -- : Writing /var/www/discourse/public/assets/docs/yuidoc-d4a0515b77168bf39e922e83e51c6c53e4d0d026424d18632579fb780e62823d.json
I, [2021-05-22T11:27:42.386401 #823]  INFO -- : Writing /var/www/discourse/public/assets/package-89430df3287fe61d0f8534418ae794baab30d0aea26ec8eca39e94e32a1cea6c.json
I, [2021-05-22T11:27:42.432033 #823]  INFO -- : Writing /var/www/discourse/public/assets/pretty-text/package-9b7e47e8ab5f73ce508614902e7920be951b8398b7942fe135a53a9dfac70e0a.json
I, [2021-05-22T11:27:42.465598 #823]  INFO -- : Writing /var/www/discourse/public/assets/select-kit/package-5d7a383f851d7d123cfe00a079a81c19bc4b0446fff3e2ac9f03dea6e616db18.json
I, [2021-05-22T11:27:42.515924 #823]  INFO -- : Writing /var/www/discourse/public/assets/truth-helpers/package-30cce0a3e97aa08783315a3f6c2474b73ce955ca8e03d05d572193d974b2ab85.json
I, [2021-05-22T11:27:42.567721 #823]  INFO -- : Writing /var/www/discourse/public/assets/yarn-f6f60cce0846644ac438911e5383df836c74d55acb5161c5a3c0bfb9a237a1e5.lock
MaxMind IP database updates require a license
Please set DISCOURSE_MAXMIND_LICENSE_KEY to one you generated at https://www.maxmind.com
MaxMind IP database updates require a license
Please set DISCOURSE_MAXMIND_LICENSE_KEY to one you generated at https://www.maxmind.com
12254643.990115996 Compressing: vendor-dde8b5f2dd41adf78c88e7719455c3a5d4db146cb96d783a2dc1ed978892f200.js
terser '/var/www/discourse/public/assets/_vendor-dde8b5f2dd41adf78c88e7719455c3a5d4db146cb96d783a2dc1ed978892f200.js' -m -c -o '/var/www/discourse/public/assets/vendor-dde8b5f2dd41adf78c88e7719455c3a5d4db146cb96d783a2dc1ed978892f200.js' --source-map "base='/var/www/discourse/public/assets',root='/assets',url='/assets/vendor-dde8b5f2dd41adf78c88e7719455c3a5d4db146cb96d783a2dc1ed978892f200.js.map'"
gzip -f -c -9 /var/www/discourse/public/assets/vendor-dde8b5f2dd41adf78c88e7719455c3a5d4db146cb96d783a2dc1ed978892f200.js > /var/www/discourse/public/assets/vendor-dde8b5f2dd41adf78c88e7719455c3a5d4db146cb96d783a2dc1ed978892f200.js.gz

brotli -f --quality=11 /var/www/discourse/public/assets/vendor-dde8b5f2dd41adf78c88e7719455c3a5d4db146cb96d783a2dc1ed978892f200.js --output=/var/www/discourse/public/assets/vendor-dde8b5f2dd41adf78c88e7719455c3a5d4db146cb96d783a2dc1ed978892f200.js.br


Done compressing vendor-dde8b5f2dd41adf78c88e7719455c3a5d4db146cb96d783a2dc1ed978892f200.js : 20.08 secs

12254664.101385953 Compressing: admin-278b157077ae2009bfaf0b96568c5bfffbf9fb075568769e5e10c6c16475425a.js
terser '/var/www/discourse/public/assets/_admin-278b157077ae2009bfaf0b96568c5bfffbf9fb075568769e5e10c6c16475425a.js' -m -c -o '/var/www/discourse/public/assets/admin-278b157077ae2009bfaf0b96568c5bfffbf9fb075568769e5e10c6c16475425a.js' --source-map "base='/var/www/discourse/public/assets',root='/assets',url='/assets/admin-278b157077ae2009bfaf0b96568c5bfffbf9fb075568769e5e10c6c16475425a.js.map'"
gzip -f -c -9 /var/www/discourse/public/assets/admin-278b157077ae2009bfaf0b96568c5bfffbf9fb075568769e5e10c6c16475425a.js > /var/www/discourse/public/assets/admin-278b157077ae2009bfaf0b96568c5bfffbf9fb075568769e5e10c6c16475425a.js.gz

brotli -f --quality=11 /var/www/discourse/public/assets/admin-278b157077ae2009bfaf0b96568c5bfffbf9fb075568769e5e10c6c16475425a.js --output=/var/www/discourse/public/assets/admin-278b157077ae2009bfaf0b96568c5bfffbf9fb075568769e5e10c6c16475425a.js.br


Done compressing admin-278b157077ae2009bfaf0b96568c5bfffbf9fb075568769e5e10c6c16475425a.js : 26.64 secs

12254690.760328608 Compressing: browser-detect-115ab5953de1b5bb122bfb26b757f5391dd8d1d2aef2b81baf7b59aee99d9f34.js
terser '/var/www/discourse/public/assets/_browser-detect-115ab5953de1b5bb122bfb26b757f5391dd8d1d2aef2b81baf7b59aee99d9f34.js' -m -c -o '/var/www/discourse/public/assets/browser-detect-115ab5953de1b5bb122bfb26b757f5391dd8d1d2aef2b81baf7b59aee99d9f34.js' --source-map "base='/var/www/discourse/public/assets',root='/assets',url='/assets/browser-detect-115ab5953de1b5bb122bfb26b757f5391dd8d1d2aef2b81baf7b59aee99d9f34.js.map'"
gzip -f -c -9 /var/www/discourse/public/assets/browser-detect-115ab5953de1b5bb122bfb26b757f5391dd8d1d2aef2b81baf7b59aee99d9f34.js > /var/www/discourse/public/assets/browser-detect-115ab5953de1b5bb122bfb26b757f5391dd8d1d2aef2b81baf7b59aee99d9f34.js.gz

brotli -f --quality=11 /var/www/discourse/public/assets/browser-detect-115ab5953de1b5bb122bfb26b757f5391dd8d1d2aef2b81baf7b59aee99d9f34.js --output=/var/www/discourse/public/assets/browser-detect-115ab5953de1b5bb122bfb26b757f5391dd8d1d2aef2b81baf7b59aee99d9f34.js.br


Done compressing browser-detect-115ab5953de1b5bb122bfb26b757f5391dd8d1d2aef2b81baf7b59aee99d9f34.js : 1.35 secs

12254692.107551016 Compressing: browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js
terser '/var/www/discourse/public/assets/_browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js' -m -c -o '/var/www/discourse/public/assets/browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js' --source-map "base='/var/www/discourse/public/assets',root='/assets',url='/assets/browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js.map'"
gzip -f -c -9 /var/www/discourse/public/assets/browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js > /var/www/discourse/public/assets/browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js.gz

brotli -f --quality=11 /var/www/discourse/public/assets/browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js --output=/var/www/discourse/public/assets/browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js.br


Done compressing browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js : 0.74 secs

12254692.85280978 Compressing: break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js
terser '/var/www/discourse/public/assets/_break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js' -m -c -o '/var/www/discourse/public/assets/break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js' --source-map "base='/var/www/discourse/public/assets',root='/assets',url='/assets/break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js.map'"
gzip -f -c -9 /var/www/discourse/public/assets/break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js > /var/www/discourse/public/assets/break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js.gz

brotli -f --quality=11 /var/www/discourse/public/assets/break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js --output=/var/www/discourse/public/assets/break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js.br


Done compressing break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js : 0.71 secs

12254693.56755353 Compressing: ember_jquery-36a23101c869ab0dc53fc908de69adb785731593573d32bdeef416acc1076ef4.js
terser '/var/www/discourse/public/assets/_ember_jquery-36a23101c869ab0dc53fc908de69adb785731593573d32bdeef416acc1076ef4.js' -m -c -o '/var/www/discourse/public/assets/ember_jquery-36a23101c869ab0dc53fc908de69adb785731593573d32bdeef416acc1076ef4.js' --source-map "base='/var/www/discourse/public/assets',root='/assets',url='/assets/ember_jquery-36a23101c869ab0dc53fc908de69adb785731593573d32bdeef416acc1076ef4.js.map'"
Killed
I, [2021-05-22T11:57:24.052654 #1]  INFO -- : Downloading MaxMindDB...
Compressing Javascript and Generating Source Maps

I, [2021-05-22T11:57:24.091597 #1]  INFO -- : Terminating async processes
I, [2021-05-22T11:57:24.092817 #1]  INFO -- : Sending INT to HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/13/bin/postmaster -D /etc/postgresql/13/main pid: 54
I, [2021-05-22T11:57:24.094687 #1]  INFO -- : Sending TERM to exec chpst -u redis -U redis /usr/bin/redis-server /etc/redis/redis.conf pid: 171
171:signal-handler (1621684644) Received SIGTERM scheduling shutdown...
2021-05-22 11:57:24.102 UTC [54] LOG:  received fast shutdown request
2021-05-22 11:57:24.179 UTC [54] LOG:  aborting any active transactions
171:M 22 May 2021 11:57:24.196 # User requested shutdown...
171:M 22 May 2021 11:57:24.197 * Saving the final RDB snapshot before exiting.
2021-05-22 11:57:24.202 UTC [54] LOG:  background worker "logical replication launcher" (PID 63) exited with exit code 1
2021-05-22 11:57:24.205 UTC [58] LOG:  shutting down
171:M 22 May 2021 11:57:24.353 * DB saved on disk
171:M 22 May 2021 11:57:24.354 # Redis is now ready to exit, bye bye...
2021-05-22 11:57:24.657 UTC [54] LOG:  database system is shut down


FAILED
--------------------
Pups::ExecError: cd /var/www/discourse && su discourse -c 'bundle exec rake themes:update assets:precompile' failed with return #<Process::Status: pid 821 exit 137>
Location of failure: /pups/lib/pups/exec_command.rb:112:in `spawn'
exec failed with the params {"cd"=>"$home", "hook"=>"assets_precompile", "cmd"=>["su discourse -c 'bundle exec rake themes:update assets:precompile'"]}
1a179ebaf86f73f20e5e0db798e912cd433a410cdc700b3cf822e63d95b3d51c
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one.
./discourse-doctor may help diagnose the problem.
==================== END REBUILD LOG ====================
Failed to rebuild app.

Checking your domain name . . .

Connection to testing.privacylx.org succeeded.
You should probably remove any non-standard plugins and rebuild.
Attempting to restart existing container. . . 

+ /usr/bin/docker run --shm-size=512m -d --restart=always -e LANG=en_US.UTF-8 -e RAILS_ENV=production -e UNICORN_WORKERS=3 -e UNICORN_SIDEKIQS=1 -e RUBY_GLOBAL_METHOD_CACHE_SIZE=131072 -e RUBY_GC_HEAP_GROWTH_MAX_SLOTS=40000 -e RUBY_GC_HEAP_INIT_SLOTS=400000 -e RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.5 -e DISCOURSE_DB_SOCKET=/var/run/postgresql -e DISCOURSE_DB_HOST= -e DISCOURSE_DB_PORT= -e LETSENCRYPT_DIR=/shared/letsencrypt -e DISCOURSE_DEFAULT_LOCALE=en -e DISCOURSE_HOSTNAME=testing.privacylx.org -e DOCKER_USE_HOSTNAME=false -e DISCOURSE_DEVELOPER_EMAILS=cafe-testing@privacylx.org -e DISCOURSE_SMTP_ADDRESS=mail.privacylx.org -e DISCOURSE_SMTP_PORT=587 -e DISCOURSE_SMTP_USER_NAME=cafe-testing@privacylx.org -e DISCOURSE_SMTP_PASSWORD=ShortenHexagramFlyoverConcludeSanctitySketchGrinningLurchUnmoving -e DISCOURSE_SMTP_ENABLE_START_TLS=true -e LETSENCRYPT_ACCOUNT_EMAIL=cafe-testing@privacylx.org -h testing-app -e DOCKER_HOST_IP=172.17.0.1 --name app -t -p 80:80 -p 443:443 -v /var/discourse/shared/standalone:/shared --mac-address 02:99:48:09:2c:b2 local_discourse/app /sbin/boot
Unable to find image 'local_discourse/app:latest' locally
docker: Error response from daemon: pull access denied for local_discourse/app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Failed to restart the container.


```

**Comment by anadahz** [comment]
@francisco-core The error was related to Docker rate limits, restarted the CI build and completes successfully. 
See Travis build log: https://travis-ci.org/github/PrivacyLx/devops/jobs/771950730

BTW I pushed some lint fixes in https://github.com/PrivacyLx/devops/pull/65/commits/caac28910991f1a1254ea1c469431958ff43abc3 .

Sorry for push merging.

**Comment by anadahz** [comment]
@francisco-core Ready to merge and deploy.

**Comment by francisco-core** [comment]
Epic! Deployed. Merging. Thanks for taking a look.

**Pull request merged**
