### PR TITLE
Bump up CI dependencies version

### PR DESCRIPTION
**Pull request by anadahz**

### CODE REVIEW

**Comment by anadahz** [comment]
Upstream issue tracking: https://github.com/pypa/pipenv/issues/4888

**Comment by francisco-core** [comment]
> Upstream issue tracking: [pypa/pipenv#4888](https://github.com/pypa/pipenv/issues/4888)

They say it may be because we have an outdate pip version. Can you check that's the issue.

**Comment by anadahz** [comment]
> They say it may be because we have an outdate pip version. Can you check that's the issue.

Same issue also with an pipenv older version.
Also the CI is running the same version (21.3.1) as in https://github.com/pypa/pipenv/issues/4888#issuecomment-997327407

CI log: https://github.com/PrivacyLx/devops/runs/4609446619?check_suite_focus=true#step:8:9

**Comment by anadahz** [comment]
I removed the `pipenv check` step in https://github.com/PrivacyLx/devops/pull/84/commits/d5ee9950c0bb70f8a0ccc73bdf3bd1b76f6e836f  and this "workaround" seems to work

**Comment by anadahz** [comment]
@francisco-core LGTM?

**Review by francisco-core — APPROVED** [review]

**Pull request merged**
