### PR TITLE
Testing of Discourse role with Travis and Vagrant

### PR DESCRIPTION
**Pull request by anadahz**
Support for testing Ansible roles with Molecule. The Vagrant platform is
being used in order to be able and test Ansible playbook roles that
deploy and use Docker containers. Molecule does not support Docker
inside Docker testing and Vagrant help us to test our roles as accurate
as possible without workarounds or extra modifications.

This commit introduces default variables required by Molecule which is
useful for others in case they want to use the Discourse role in their
setup. Additionally it's fixing the faulty conditionals in Discourse
role. Furthermore it adds an Asnible inventory specifically for Molecule
testing.

Molecule does linting and syntax checking, deploys the playbook role,
checks if playbook is idempotent and finally runs some preliminary
tests; checks if Docker daemon is up and running on the testing
platforms.

### CODE REVIEW

**Comment by francisco-core** [comment]
Thanks for all the hard work on this!

Do you think you could provide some instructions on how this can be ran and tested?

**Comment by anadahz** [comment]
> Do you think you could provide some instructions on how this can be ran and tested?

Travis is installing Vagrant and then calls Molecule to test the role.
See: https://github.com/PrivacyLx/devops/blob/128078d0b301e08cc106ed11c7a8f8a31b31e9a1/.travis.yml

Travis will now run in every branch and pull request and it will display a fail/run/running icon next to the git commit. You can follow Travis CI build flow here:
https://github.com/PrivacyLx/devops/runs/554923114

**Comment by francisco-core** [comment]
It looks good to me, but I think it would be important to inform whoever made a commit about which role is being tested and how to change it. Just in case either of us forgets or someone else joins the team.

I would propose we change the `scripts` part of the `.travis` to:
```yaml
script:
  - |
    echo "######################################################################"
    echo "# Running role: $TEST_ROLE
    echo "# To change testing role, edit .travis to change the variable \$TEST_ROLE"
    echo "######################################################################"
 
    cd ansible/roles/$TEST_ROLE
    sudo -E pipenv run molecule lint
    sudo -E pipenv run molecule syntax
    travis_wait 30 sudo -E pipenv run molecule converge
    travis_wait 30 sudo -E pipenv run molecule idempotence
```

What do you think?

**Comment by francisco-core** [comment]
^ there is a missing `"` on one of the echo commands and for some reason I can't edit it

**Comment by anadahz** [comment]
@francisco-core Thank you for reviewing this PR.

> I would propose we change the scripts part of the .travis to:

There is no need to change the script just add the name of the role in jobs as in: https://github.com/PrivacyLx/devops/pull/31/files#diff-354f30a63fb0907d4ad57269548329e3R14

**Comment by francisco-core** [comment]
I see. Ok

**Pull request merged**
