### PR TITLE
Remove leftovers files and obsolete git submodules

### PR DESCRIPTION
**Pull request by anadahz**
* Remove all git submodules and their files
* Remove obsolete Ansible role file

### CODE REVIEW

**Comment by francisco-core** [comment]
Only one thing: by removing the `onion-services` are we fully removing it? or just the fact that is a submodule? Because those files are needed for the current version (although a bit broken)

**Comment by anadahz** [comment]
> Only one thing: by removing the `onion-services` are we fully removing it? or just the fact that is a submodule? Because those files are needed for the current version (although a bit broken)

This can be safely removed as  the `onion-services` directory is not used anymore, please see:
https://github.com/PrivacyLx/devops/commit/048edbc95e7c00f6f780599112ae16fb1cc5613e

**Comment by francisco-core** [comment]
I think we should have done this another way. How do we go about updating the sub-module from upstream? Downloading a copy and making a commit for it?

**Comment by francisco-core** [comment]
what's the status of this? Does it still make sense to be merged. If so, please go ahead.

**Comment by anadahz** [comment]
> what's the status of this? Does it still make sense to be merged. If so, please go ahead.

Yes it does make sense to merge as these old files are not required.
Merging!

**Pull request merged**
