### PR TITLE
Add Tor relay role, fix admin role in newer Ansible version

### PR DESCRIPTION
**Pull request by anadahz**
- Add Tor relay role config and bootstrap nusenu.relayor
- Add testing inventory
- Fix admin role to work on newer Ansible version (thx @flowerysong)
- Add custom HTML file generated with:
  https://github.com/Strappazzon/tor-exit-page
- Admin role: disable password for root

### CODE REVIEW

**Review by francisco-core — COMMENTED** [review]
Shouldn't the relay's private keys be set as an ansible variable? If it ever gets wiped, I don't want us to loose it... Apart from that I think it's good to be merged

**Comment by anadahz** [comment]
> Shouldn't the relay's private keys be set as an ansible variable? If it ever gets wiped, I don't want us to loose it... Apart from that I think it's good to be merged

Is this possible? If yes how?

**Review by francisco-core — APPROVED** [review]
LGTM

**Comment by francisco-core** [comment]
Is this running well locally and just failing on github actions?

**Comment by anadahz** [comment]
> Is this running well locally and just failing on github actions?

Yes.

The issue is that the CI is using a "centralized/common DNS resolver" (Google, Quad9, CloudFlare, OpenDNS, Level3).
See: https://github.com/PrivacyLx/devops/pull/70/checks?check_run_id=3444443065#step:8:1362

I should add a task to change the default DNS resolver during CI checks.

**Review by francisco-core — APPROVED** [review]

**Pull request merged**
