### PR TITLE
Fix website role (fixes #25, #26, #16)

### PR DESCRIPTION
**Pull request by anadahz**
This commit is almost a complete rewrite of the website role, that uses
Caddy to host the website, checkouts and builds the website once new
contect (on master branch) is detected (on a 5 minute interval rate).
Onion services version 2 and 3 are now working and use a different
network than localhost for accidental leaks or issues with localhost
bidning of onion services.

Resolves:
* https://github.com/PrivacyLx/privacylx-issue-tracker/issues/16
* https://github.com/PrivacyLx/privacylx-issue-tracker/issues/25
* https://github.com/PrivacyLx/privacylx-issue-tracker/issues/26

* No need for submodules, update README
* Rename caddy-website to website
* Fix order of deployment roles, docker should be before website
* Move some known public variables to group_vars
* Cleanup: remove broken, obsolete and other non required files
* Update privacylx.org host variables, SSH known_hosts, and inventory

### CODE REVIEW

**Comment by francisco-core** [comment]
I'm having trouble testing this locally. The role runs fine but, but I cannot reach localhost to see the end result. How have you been testing it?

**Comment by anadahz** [comment]
> I'm having trouble testing this locally. The role runs fine but, but I cannot reach localhost to see the end result. 

How do you run the role?

> How have you been testing it?

I created a testing VM and chages all references of `privacylx.org` to `testingvm`.
Also change the variables in https://github.com/PrivacyLx/devops/tree/master/ansible/inventory/host_vars/privacylx.org so that it will not mess with the production website.

Ideally we should be adding support to test Ansible roles.

**Comment by francisco-core** [comment]
I'm having issues with "le_staging: true".

```txt
Activating privacy features... 2019/08/13 03:57:01 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 03:57:02 [INFO] [privacylx.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882179
2019/08/13 03:57:02 [INFO] [privacylx.org] acme: Could not find solver for: tls-alpn-01
2019/08/13 03:57:02 [INFO] [privacylx.org] acme: use http-01 solver
2019/08/13 03:57:02 [INFO] [privacylx.org] acme: Trying to solve HTTP-01
2019/08/13 03:57:09 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882179
2019/08/13 03:57:10 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 03:57:10 [INFO] [privacylx.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882197
2019/08/13 03:57:10 [INFO] [privacylx.org] acme: Could not find solver for: tls-alpn-01
2019/08/13 03:57:10 [INFO] [privacylx.org] acme: use http-01 solver
2019/08/13 03:57:10 [INFO] [privacylx.org] acme: Trying to solve HTTP-01
2019/08/13 03:57:17 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882197
2019/08/13 03:57:18 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 03:57:19 [INFO] [privacylx.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882209
2019/08/13 03:57:19 [INFO] [privacylx.org] acme: Could not find solver for: tls-alpn-01
2019/08/13 03:57:19 [INFO] [privacylx.org] acme: use http-01 solver
2019/08/13 03:57:19 [INFO] [privacylx.org] acme: Trying to solve HTTP-01
2019/08/13 03:57:27 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882209
2019/08/13 03:57:28 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 03:57:29 [INFO] [privacylx.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882224
2019/08/13 03:57:29 [INFO] [privacylx.org] acme: use tls-alpn-01 solver
2019/08/13 03:57:29 [INFO] [privacylx.org] acme: Trying to solve TLS-ALPN-01
2019/08/13 03:57:30 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882224
2019/08/13 03:57:31 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 03:57:31 [INFO] [privacylx.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882227
2019/08/13 03:57:31 [INFO] [privacylx.org] acme: use tls-alpn-01 solver
2019/08/13 03:57:31 [INFO] [privacylx.org] acme: Trying to solve TLS-ALPN-01
2019/08/13 03:57:32 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882227
2019/08/13 03:57:33 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 03:57:34 [INFO] [privacylx.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882235
2019/08/13 03:57:34 [INFO] [privacylx.org] acme: use tls-alpn-01 solver
2019/08/13 03:57:34 [INFO] [privacylx.org] acme: Trying to solve TLS-ALPN-01
2019/08/13 03:57:40 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3882235
2019/08/13 03:57:41 failed to obtain certificate: acme: Error -> One or more domains had a problem:
[privacylx.org] acme: error: 400 :: urn:ietf:params:acme:error:tls :: remote error: tls: internal error, url: 
exit status 1
```

and later on some rate-limiting by letsencrypt:
```txt
Activating privacy features... 2019/08/13 04:23:43 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 04:23:44 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 04:23:46 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 04:23:47 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 04:23:49 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 04:23:50 [INFO] [privacylx.org] acme: Obtaining bundled SAN certificate
2019/08/13 04:23:52 failed to obtain certificate: acme: error: 429 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: 
exit status 1
```

And the container keeps on restarting. Do you know what this can be related to?

**Comment by francisco-core** [comment]
> and later on some rate-limiting by letsencrypt:

This must have been due to the following

> The Failed Validations limit is 60 per hour.
> -- from https://letsencrypt.org/docs/staging-environment/

I don't exactly know how the tls negotiation works, but it might be related with the firewall, actually.

> HTTP validation happens on port 80, so it will have to open on your firewall(s). Let's Encrypt doesn't disclose IP address range(s) for their validation servers, meaning port 80 will have to be accessible from any origin, at least for the duration of the validation.

**Comment by anadahz** [comment]
> I'm having issues with "le_staging: true".

Was this the only change you made?
Could you please enable verbosity in Ansible roles and post the relevant output?

**Comment by francisco-core** [comment]
Sorry for the delay. The following is the only relevant info I found on ansible's output:

```txt
    ok: [testing] => {
        "actions": [],
        "ansible_facts": {
            "www": {
                "privacylxorg_www_1": {
                    "cmd": [
                        "-conf",
                        "/etc/Caddyfile",
                        "-agree",
                        "-ca",
                        "https://acme-staging-v02.api.letsencrypt.org/directory"
                    ],
                    "image": "privacylx.org-image",
                    "labels": {
                        "caddy_version": "1.0.1",
                        "com.docker.compose.config-hash": "084653f66461e1c10ff2c0d4e1b2c25ba3b04e894c5ab32c012158b227449c51",
                        "com.docker.compose.container-number": "1",
                        "com.docker.compose.oneoff": "False",
                        "com.docker.compose.project": "privacylxorg",
                        "com.docker.compose.service": "www",
                        "com.docker.compose.version": "1.24.1"
                    },
                    "networks": {
                        "privacylxorg_static-network": {
                            "IPAddress": "172.3.27.2",
                            "IPPrefixLen": 30,
                            "aliases": [
                                "www",
                                "462b363f67b2"
                            ],
                            "globalIPv6": "",
                            "globalIPv6PrefixLen": 0,
                            "links": null,
                            "macAddress": "02:42:ac:03:1b:02"
                        }
                    },
                    "state": {
                        "running": true,
                        "status": "running"
                    }
                }
            }
        },
        "changed": false,
        "invocation": {
            "module_args": {
                "api_version": "auto",
                "build": false,
                "ca_cert": null,
                "client_cert": null,
                "client_key": null,
                "debug": false,
                "definition": {
                    "networks": {
                        "static-network": {
                            "ipam": {
                                "config": [
                                    {
                                        "subnet": "172.3.27.0/30"
                                    }
                                ]
                            }
                        }
                    },
                    "services": {
                        "www": {
                            "image": "privacylx.org-image",
                            "networks": {
                                "static-network": {
                                    "ipv4_address": "172.3.27.2"
                                }
                            },
                            "ports": [
                                "80:80/tcp",
                                "443:443/tcp"
                            ],
                            "restart": "always",
                            "volumes": [
                                "/opt/caddy/Caddyfile:/etc/Caddyfile",
                                "/opt/caddycerts:/etc/caddycerts"
                            ]
                        }
                    },
                    "version": "2"
                },
                "dependencies": true,
                "docker_host": "unix://var/run/docker.sock",
                "files": null,
                "hostname_check": false,
                "nocache": false,
                "project_name": "privacylx.org",
                "project_src": null,
                "pull": false,
                "recreate": "smart",
                "remove_images": null,
                "remove_orphans": false,
                "remove_volumes": false,
                "restarted": false,
                "scale": null,
                "services": null,
                "ssl_version": null,
                "state": "present",
                "stopped": false,
                "timeout": 10,
                "tls": false,
                "tls_hostname": "localhost",
                "validate_certs": false
            }
        },
        "services": {
            "www": {
                "privacylxorg_www_1": {
                    "cmd": [
                        "-conf",
                        "/etc/Caddyfile",
                        "-agree",
                        "-ca",
                        "https://acme-staging-v02.api.letsencrypt.org/directory"
                    ],
                    "image": "privacylx.org-image",
                    "labels": {
                        "caddy_version": "1.0.1",
                        "com.docker.compose.config-hash": "084653f66461e1c10ff2c0d4e1b2c25ba3b04e894c5ab32c012158b227449c51",
                        "com.docker.compose.container-number": "1",
                        "com.docker.compose.oneoff": "False",
                        "com.docker.compose.project": "privacylxorg",
                        "com.docker.compose.service": "www",
                        "com.docker.compose.version": "1.24.1"
                    },
                    "networks": {
                        "privacylxorg_static-network": {
                            "IPAddress": "172.3.27.2",
                            "IPPrefixLen": 30,
                            "aliases": [
                                "www",
                                "462b363f67b2"
                            ],
                            "globalIPv6": "",
                            "globalIPv6PrefixLen": 0,
                            "links": null,
                            "macAddress": "02:42:ac:03:1b:02"
                        }
                    },
                    "state": {
                        "running": true,
                        "status": "running"
                    }
                }
            }
        }
    }

```

But it doesn't show any error there. So you were able to get the staging certificate running locally, right?

**Comment by anadahz** [comment]
> But it doesn't show any error there. So you were able to get the staging certificate running locally, right?

Anything related on the `docker logs` of the containers?

**Comment by francisco-core** [comment]
@anadahz with the test server things went smoothly. Thanks.
Plase review also my commit for adding information and code for the staging

**Comment by anadahz** [comment]
@francisco-core Great, thank for the review and the testing contribution.
Proceeding with merging and deploying the role

**Pull request merged**
